### ISSUE TITLE
Undefined flag in Cabal file

### ISSUE THREAD

**Issue by lwm** [haskell-works/hw-prim-bits#2]
When building this package on Stackage, I see the following output:

```
FlagNotDefined (PackageName "hw-prim-bits") (FlagName "sse42") (Var (Flag (FlagName "sse42")))
```

Seems like you're missing a flag definition.

**Comment by newhoggy** [comment]
Fixed in `0.1.0.2`

https://circleci.com/gh/haskell-works/hw-prim-bits/23
